# Generated by Django 4.1.7 on 2023-06-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMascotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
