# Generated by Django 4.1.7 on 2023-05-18 01:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appMascotas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id_comunidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Comunidad',
                'verbose_name_plural': 'Comunidades',
                'db_table': 'Comunidad',
            },
        ),
        migrations.RenameField(
            model_name='duenomascota',
            old_name='id_paseador',
            new_name='fk_paseador',
        ),
        migrations.RenameField(
            model_name='duenomascota',
            old_name='id_peluqueria',
            new_name='fk_peluqueria',
        ),
        migrations.RenameField(
            model_name='duenomascota',
            old_name='id_veterinaria',
            new_name='fk_veterinaria',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='id_dueno_mascota',
            new_name='fk_dueno_mascota',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='id_veterinaria',
            new_name='fk_veterinaria',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='id_dueno_mascota',
            new_name='fk_dueno_mascota',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='id_paseador',
            new_name='fk_paseador',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='id_peluqueria',
            new_name='fk_peluqueria',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='id_registro_mascota',
            new_name='fk_registro_mascota',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='id_veterinaria',
            new_name='fk_veterinaria',
        ),
        migrations.RenameField(
            model_name='paseador',
            old_name='id_comunidad',
            new_name='fk_posteo',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='id_veterinaria',
            new_name='fk_veterinaria',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='id_dueno_mascota',
            new_name='fk_dueno_mascota',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='id_paseador',
            new_name='fk_paseador',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='id_peluqueria',
            new_name='fk_peluqueria',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='id_veterinaria',
            new_name='fk_veterinaria',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='id_dueno_mascota',
            new_name='fk_dueno_mascota',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='id_paseador',
            new_name='fk_paseador',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='id_peluqueria',
            new_name='fk_peluqueria',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='id_veterinaria',
            new_name='fk_veterinaria',
        ),
        migrations.RemoveField(
            model_name='duenomascota',
            name='id_comunidad',
        ),
        migrations.RemoveField(
            model_name='duenomascota',
            name='id_factura',
        ),
        migrations.RemoveField(
            model_name='peluqueriacanina',
            name='id_comunidad',
        ),
        migrations.RemoveField(
            model_name='veterinaria',
            name='id_comunidad',
        ),
        migrations.RemoveField(
            model_name='veterinaria',
            name='id_factura',
        ),
        migrations.AddField(
            model_name='avatar',
            name='fk_dueno_mascota',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appMascotas.duenomascota'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='fk_paseador',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appMascotas.paseador'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='fk_peluqueria',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appMascotas.peluqueriacanina'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='fk_veterinaria',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appMascotas.veterinaria'),
        ),
        migrations.AddField(
            model_name='factura',
            name='fk_peluquerias',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appMascotas.peluqueriacanina'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='comentarios',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='contenido',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='grupo',
            name='fk_dueno_mascota',
            field=models.ManyToManyField(to='appMascotas.duenomascota'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='fk_paseador',
            field=models.ManyToManyField(to='appMascotas.paseador'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='fk_peluqueria',
            field=models.ManyToManyField(to='appMascotas.peluqueriacanina'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='fk_veterinaria',
            field=models.ManyToManyField(to='appMascotas.veterinaria'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='imagen',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='imagen_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='peluqueriacanina',
            name='fk_factura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMascotas.factura'),
        ),
        migrations.AddField(
            model_name='veterinaria',
            name='fk_comunidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMascotas.posteo'),
        ),
        migrations.AlterField(
            model_name='duenomascota',
            name='calle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='duenomascota',
            name='numero',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_vencimiento',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='forma_pago',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tipo',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='peluqueriacanina',
            name='productos',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='peluqueriacanina',
            name='servicios',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='img-producto/default.jpg', upload_to='img-producto'),
        ),
        migrations.AlterField(
            model_name='registromascota',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='registromascota',
            name='nacimiento',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='registromascota',
            name='patologia',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='registromascota',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='registromascota',
            name='raza',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='a_domicilio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='cercanas',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='de_guardia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='veterinaria',
            name='productos',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='veterinaria',
            name='servicios',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='duenomascota',
            name='fk_comunidad',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appMascotas.comunidad'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='fk_comunidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMascotas.comunidad'),
        ),
        migrations.AddField(
            model_name='paseador',
            name='fk_comunidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMascotas.comunidad'),
        ),
        migrations.AddField(
            model_name='peluqueriacanina',
            name='fk_comunidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMascotas.comunidad'),
        ),
        migrations.AddField(
            model_name='posteo',
            name='fk_comunidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMascotas.comunidad'),
        ),
    ]
